<template>
  <div id="app">
      <button
          v-for="tab in tabs"
          v-bind:key="tab"
          v-on:click="currentTab = tab"
          class="tab-button"
      >
          {{ tab }}
      </button>
      <keep-alive>
        <component v-bind:is="currentTab"></component>
      </keep-alive>
      <NotificationContainer/>
  </div>
</template>

<script>
import TermManager from './views/TermManager/TermManager';
import UserManager from './views/UserManager/UserManager';
import SuggestionManager from './views/SuggestionManager/SuggestionManager';
import NotificationContainer from './components/NotificationContainer'
import * as Diff2Html from 'diff2html';
import 'diff2html/bundles/css/diff2html.min.css';
export default {
    components: {
        TermManager,
        UserManager,
        SuggestionManager,
        NotificationContainer
    },
    data() {
        return {
            currentTab: "TermManager",
            tabs: ["UserManager", "TermManager", "SuggestionManager"],
            diffs: '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error)'
        }
    },
    computed: {
        prettyHtml() {
            return Diff2Html.html(this.diffs, {
                drawFileList: false,
                matching: 'lines',
                outputFormat: 'side-by-side',
            });
        },
    }
}
</script>

<style>
@import url('https://fonts.googleapis.com/css?family=Poppins');

body {
  background-color: #f8fcfd;
  font-family: Verdana, sans-serif;
  color: #747474;
  font-size: 13px;
}

.router-link {
  margin-right: 10px;
  display: inline-block;
}

.tab-button {
  margin: 5px;
}

</style>